environment:
  RUST_BACKTRACE: 1
  matrix:
    # 32-bit
    - RUST_HOST: i686-pc-windows-msvc
      RUST_VERSION: stable
    # 64-bit
    - RUST_HOST: x86_64-pc-windows-msvc
      RUST_VERSION: stable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - cargo run

build: off
