# TODO: Maybe add caching
cache:
  - '%HOMEDRIVE%%HOMEPATH%\.cargo -> .appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.multirust -> .appveyor.yml'

environment:
  RUST_BACKTRACE: 1
  matrix:
    # 32-bit
    - RUST_HOST: i686-pc-windows-msvc
      RUST_VERSION: stable
    # 64-bit
    - RUST_HOST: x86_64-pc-windows-msvc
      RUST_VERSION: stable

install:
  - set PATH="C:\Program Files (x86)\MSBuild\%TOOLCHAIN_VERSION%\Bin;%HOMEDRIVE%%HOMEPATH%\.cargo\bin;%PATH%""
  - echo %PATH%
  - IF NOT EXIST %HOMEDRIVE%%HOMEPATH%\.cargo\bin (curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain %RUST_VERSION% --default-host %RUST_HOST% -y)
  - rustup default %RUST_VERSION%-%RUST_HOST%

test_script:
  - cargo run

build: off
